### ISSUE TITLE
Issues with delete

### ISSUE THREAD

**Issue by neotropic2023** [anzawi/php-database-class#16]
$db->table(TABLE_CATEGOREIS)->where('cid', $this->r['id'])->delete(); 
Simply dies, no errors at all.  Could it be 'delete()'?
		
$db->table(TABLE_CATEGOREIS)->find($this->r['id'])->delete(); 
Looks for ID, but I am using CID

I am on localhost using XAMPP PHP 7
Everything else so far seems to be working. But only doing simple selects right now, until I get deeper in my project.

**Comment by neotropic2023** [comment]
Ya, I tired numerous methods.
First I am selecting the image to get it to delete the attached image.
Then I am trying to delete the record. 

On delete.php "$results = (array)$this->_results;". 
I was printing out the results. It kept showing me results from my first call. Showing me the image value of the first all. $this->count() was always 1.

```
$query = "SELECT image FROM ".TABLE_CATEGOREIS." WHERE cid=".$this->r['id'];
$results = $db->query($query)->results();
if($results[0]){
	@unlink(_PATH_IMAGES.'categories/'.$results[0]->image);
}
```
Then I was trying
`$db->table(TABLE_CATEGOREIS)->where('cid', $this->r['id'])->delete();`

No go. So now... this works:
```
$query = "DELETE FROM ".TABLE_CATEGOREIS." WHERE cid=".$this->r['id'];
$db->query($query);
```
It could be I am doing something wrong. 
I got to lazy to write a new class for PHP 7, so hoping to try and use yours instead. So far so good. Just this dang delete function.

**Comment by anzawi** [comment]
sorry about that,,,
update "Delete.php"
to look like this git https://gist.github.com/anzawi/b6194632700b56406ea8649a12b52d17

you can found "Delete.php" in 
vendor/phptricks/database_class/phptricksORM/DML/Delete.php

**Comment by anzawi** [comment]
Oops, 
ya about using (cid  instead of the id)

you can use "idName()" method

```php
$db->table('test')->idName('cid')->find(1)->delete();
```

to delete image record

```php
$imageForDeleting = $db->table(TABLE_CATEGOREIS)->idName('cid')->find($this->r['id']);
@unlink(_PATH_IMAGES.'categories/' . $imageForDeleting ->image);
$imageForDeleting ->delete();
```
