### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by xlmnxp** [anzawi/php-database-class#5]
كيف أستخدم مثل هذه الطريقة في الكلاس الخاص بك
```sql
SELECT * FROM users WHERE (username LIKE '%Salem%' OR fullname LIKE '%Salem%' OR message LIKE '%Salem%') AND sex = 0 LIMIT 0, 12
```

**Comment by Abdulla2** [comment]
الق نظرة على الدوال التالية في التوثيق:
```

select
likeWhere
orWhere 
limit

```

**Comment by xlmnxp** [comment]
اخي هناك فرق كبير
عندما تستخدم where
هكذا
```sql
WHERE (username LIKE '%Salem%' OR fullname LIKE '%Salem%' OR message LIKE '%Salem%') AND sex = 0
```
او هكذا
```sql
WHERE username LIKE '%Salem%' OR fullname LIKE '%Salem%' OR message LIKE '%Salem%' AND sex = 0
```
في الثانية لن يعطي اي اهتمام لـ
```sql
AND sex = 0
```
بسبب الـ 
```sql
OR
```
التي تسبقه

اما في الطريقة الاولة يلزمة ان تكون الـ `sex` بنفس القيمة المحددة

**Comment by xlmnxp** [comment]
وجدتها هنا
https://github.com/anzawi/php-database-class/issues/1
قام باضافتها @Zsoner
في الكود الخاص به
حاول ان تضيفها لكود اخوي @anzawi 
اسم العصبه التي هو اضافها هي
parseWhere
اتمنى ان تضيفها سريعًا فهي ضرورية جدًا

**Comment by xlmnxp** [comment]
@anzawi اين انت ؟

**Comment by anzawi** [comment]
لقد تم العمل على هذا , ستكون هنالك دالة خاصة لعمل ذلك في الاصدار القادم :)
