### ISSUE TITLE
How to select with special characters?

### ISSUE THREAD

**Issue by Extarys** [anzawi/php-database-class#6]
I cannot seem to find a way to select with special characters such as " or '.

```
$name = str_replace("'", "\'", $name);
$post = $db->table('heroes')->where('name', $name)->select();
```

I'm sure it's a simple thing. I tried to look for an included function to escape characters but I cannot seem to find one.
Thanks for your help guys!

**Comment by anzawi** [comment]
thats easy! 

example: 

```php
$db = \PHPtricks\Orm\Database::connect();

$users = $db->table('users')->insert([
	'username' => "'username'",
	'password' => '"dcsds"',
	'active'   => 1
]);

`

**Comment by anzawi** [comment]
Oops! you asking about select with special characters not insert sorry !

example 

```php
$db = \PHPtricks\Orm\Database::connect();

$users = $db->table('users')
	->where('username' ,"\'username\'")
	->select();
var_dump($users->results());
```

**Comment by Extarys** [comment]
OH wow, thanks a lot - now I feel stupid :P

;)
