### ISSUE TITLE
lastInsertId, InsertOrUpdate, count

### ISSUE THREAD

**Issue by Extarys** [anzawi/php-database-class#7]
It would be nice to have a friendly count(), lastInsertID and insertorupdate method. :D

**Comment by anzawi** [comment]
yes , This has been done,  i will publish it in the next release :)
Thank you for your suggestions

**Comment by anzawi** [comment]
new version has been published !

you can see new methods here https://github.com/anzawi/php-database-class#new-in-v-410

**Comment by Extarys** [comment]
A-MA-ZING! <3 Thank you so much!
